PostoDeAssistenciaWeb/Models/Endereco.cs
using System;

namespace PostoDeAssistenciaWeb.Models
{
    public class Endereco
    {
        public Guid EnderecoId { get; set; }

        public string Uf { get; set; }

        public string Cep { get; set; }

        public string Cidade { get; set; }

        public string Bairro { get; set; }

        public string Logradouro { get; set; }

        public string Complemento { get; set; }

        //public virtual Assistido Assistido { get; set; }
    }
}

PostoDeAssistenciaWeb/Controllers/EnderecoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using PostoDeAssistenciaWeb.Integracoes.Postmon.Models;
using PostoDeAssistenciaWeb.Models;
using PostoDeAssistenciaWeb.Models.Context;

namespace PostoDeAssistenciaWeb.Controllers
{
    public class EnderecoController : Controller
    {
        private Contexto db = new Contexto();

        // GET: Endereco
        public ActionResult Index()
        {
            return View(db.Enderecos.ToList());
        }

        // GET: Endereco/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Endereco endereco = db.Enderecos.Find(id);
            if (endereco == null)
            {
                return HttpNotFound();
            }
            return View(endereco);
        }

        // GET: Endereco/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Endereco/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EnderecoId,Uf,Cidade,Bairro,Logradouro,Complemento,Cep")] Endereco endereco)
        {
            if (ModelState.IsValid)
            {
                endereco.EnderecoId = Guid.NewGuid();
                db.Enderecos.Add(endereco);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(endereco);
        }

        // GET: Endereco/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Endereco endereco = db.Enderecos.Find(id);
            if (endereco == null)
            {
                return HttpNotFound();
            }
            return View(endereco);
        }

        // POST: Endereco/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EnderecoId,Uf,Cidade,Bairro,Logradouro,Complemento,Cep")] Endereco endereco)
        {
            if (ModelState.IsValid)
            {
                db.Entry(endereco).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(endereco);
        }

        // GET: Endereco/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Endereco endereco = db.Enderecos.Find(id);
            if (endereco == null)
            {
                return HttpNotFound();
            }
            return View(endereco);
        }

        // POST: Endereco/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Endereco endereco = db.Enderecos.Find(id);
            db.Enderecos.Remove(endereco);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public JsonResult ObterPorNome(string logradouro)
        {
            var listaEnderecos = db.Enderecos.ToList();

            var filtro = listaEnderecos.Where(x =>
                            Utils.CaracterEspecial.RemoverAcentos(x.Logradouro).ToLower().Contains(Utils.CaracterEspecial.RemoverAcentos(logradouro)));

            if (filtro == null) return null;

            var serializer = new JavaScriptSerializer();

            return Json(serializer.Serialize(filtro), JsonRequestBehavior.AllowGet);
        }

        //[HttpGet]
        //public JsonResult ObterTodos()
        //{
        //    var listaEnderecos = db.Enderecos.ToList();

        //    if (listaEnderecos == null) return null;

        //    var serializer = new JavaScriptSerializer();

        //    return Json(serializer.Serialize(listaEnderecos), JsonRequestBehavior.AllowGet);
        //}

        [HttpGet]
        public JsonResult ObterPorLogradouro(string logradouro)
        {
            var listaEnderecos = db.Enderecos.ToList();

            var serializer = new JavaScriptSerializer();

            if (logradouro == null) return Json(serializer.Serialize(listaEnderecos), JsonRequestBehavior.AllowGet);

            var filtro = listaEnderecos.Where(x =>
                            Utils.CaracterEspecial.RemoverAcentos(x.Logradouro).ToLower().Contains(Utils.CaracterEspecial.RemoverAcentos(logradouro)));

            if (filtro == null) return null;

            return Json(serializer.Serialize(filtro), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public IEnumerable<Endereco> ObterTodos()
        {
            var enderecos = db.Enderecos.ToList();

            var assistidos = db.Assistidos.ToList();

            var enderecosLivres = enderecos.Where(e => !assistidos.Any(a => e.EnderecoId == a.EnderecoId));

            return enderecosLivres;
        }

        [HttpGet]
        public JsonResult ConsultarCep(string cep)
        {
            var postmon = new Integracoes.Postmon.Query();

            var response = postmon.ConsultarCep(cep);

            if (!response.EhValido) return Json(new EmptyResult(), JsonRequestBehavior.AllowGet);

            var serializer = new JavaScriptSerializer();

            return Json(serializer.Serialize(response), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ObterPorId(Guid id)
        {
            if (id == null) return Json(new EmptyResult(), JsonRequestBehavior.AllowGet);

            var endereco = db.Enderecos.Find(id);

            if (endereco == null) return Json(new EmptyResult(), JsonRequestBehavior.AllowGet);

            var serializer = new JavaScriptSerializer();

            return Json(serializer.Serialize(endereco), JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PostoDeAssistenciaWeb/Views/Endereco/Create.cshtml
@model PostoDeAssistenciaWeb.Models.Endereco

@{
    var optionsUF = new List<SelectListItem>();

    optionsUF.Add(new SelectListItem { Value = "AC", Text = "AC", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "AL", Text = "AL", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "AP", Text = "AP", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "AM", Text = "AM", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "BA", Text = "BA", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "CE", Text = "CE", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "DF", Text = "DF", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "ES", Text = "ES", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "GO", Text = "GO", Selected = true });
    optionsUF.Add(new SelectListItem { Value = "MA", Text = "MA", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "MT", Text = "MT", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "MS", Text = "MS", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "MG", Text = "MG", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "PA", Text = "PA", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "PB", Text = "PB", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "PR", Text = "PR", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "PE", Text = "PE", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "PI", Text = "PI", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "RJ", Text = "RJ", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "RN", Text = "RN", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "RS", Text = "RS", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "RO", Text = "RO", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "RR", Text = "RR", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "SC", Text = "SC", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "SP", Text = "SP", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "SE", Text = "SE", Selected = false });
    optionsUF.Add(new SelectListItem { Value = "TO", Text = "TO", Selected = false });

    ViewData["Uf"] = optionsUF;

}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="max-width: 900px">
        <h4>Endereco</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cep, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cep, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Uf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Uf", null, htmlAttributes: new { @class = "form-control", @style = "width: 120px;", required = "Informe a UF" })
                @Html.ValidationMessageFor(model => model.Uf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control", @Value = "Aparecida de Goiania" } })
                @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="width: 450px;">
                @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control", @style = "width:100%; min-width:420px;" } })
                @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Logradouro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Logradouro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Logradouro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Complemento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Complemento, 5, 40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Complemento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary" })
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@

    <script>
        $("#Cep").focusout(function () {
            $.ajax({
                type: "GET",
                url: '@Url.Action("ConsultarCep", "Endereco")',
                datatype: "json",
                data: { "cep": $("#Cep").val() },
                success: function (result) {

                    $("#Uf").val(JSON.parse(result).estado)
                    $("#Cidade").val(JSON.parse(result).cidade)
                    $("#Bairro").val(JSON.parse(result).bairro)
                    $("#Logradouro").val(JSON.parse(result).logradouro)
                }
            });
        });
    </script>
    
}

PostoDeAssistenciaWeb/Views/Endereco/Delete.cshtml
@model PostoDeAssistenciaWeb.Models.Endereco

<h4>Confirmar exclusão ?</h4>
<div>
    <h4>Endereco</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Uf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uf)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bairro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bairro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logradouro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logradouro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Complemento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Complemento)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary" })
        <input type="submit" value="Delete" class="btn btn-danger" />
    </div>
    }
</div>

<br />

PostoDeAssistenciaWeb/Views/Endereco/Details.cshtml
@model PostoDeAssistenciaWeb.Models.Endereco

<div>
    <h4>Endereco</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Uf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uf)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bairro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bairro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logradouro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logradouro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Complemento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Complemento)
        </dd>

        <dd>
            @Html.DisplayFor(model => model.Cep)
        </dd>

    </dl>
</div>
<p>
    <div class="col-md-offset-2 col-md-10">
        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary" })
        @Html.ActionLink("Editar", "Edit", new { id = Model.EnderecoId }, new { @class = "btn btn-primary" })
    </div>
</p>

<br />

PostoDeAssistenciaWeb/Views/Endereco/Edit.cshtml
@model PostoDeAssistenciaWeb.Models.Endereco


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Endereco</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.EnderecoId)

    <div class="form-group">
        @Html.LabelFor(model => model.Cep, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cep, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Uf, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Uf, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Uf, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Uf, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control", @style = "width:100%; min-width:420px;" } })
            @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Logradouro, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Logradouro, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Logradouro, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Complemento, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Complemento, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Complemento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Complemento, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Complemento, 5, 40, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Complemento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary" })
            <input type="submit" value="Salvar" class="btn btn-success" />
        </div>
    </div>
</div>

    <br />
}

@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@

    <script>
        $("#Cep").focusout(function () {
            $.ajax({
                type: "GET",
                url: '@Url.Action("ConsultarCep", "Endereco")',
                datatype: "json",
                data: { "cep": $("#Cep").val() },
                success: function (result) {

                    $("#Uf").val(JSON.parse(result).estado)
                    $("#Cidade").val(JSON.parse(result).cidade)
                    $("#Bairro").val(JSON.parse(result).bairro)
                    $("#Logradouro").val(JSON.parse(result).logradouro)
                }
            });
        });
    </script>
}

PostoDeAssistenciaWeb/Views/Endereco/Index.cshtml
@model IEnumerable<PostoDeAssistenciaWeb.Models.Endereco>

<br />


<p>
    @Html.ActionLink("Criar novo", "Create", null, new { @class = "btn btn-primary" })
</p>
<p>
    <input id="pesquisaIndexEndereco" class="form-control" style="min-width:350px" onkeyup="findIndexEndereco()" />
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Uf)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bairro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Logradouro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Complemento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cep)
        </th>
        <th></th>
    </tr>
    <tbody id="tbIndexEndereco">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Uf)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Bairro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Logradouro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Complemento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cep)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.EnderecoId }, htmlAttributes: new { @class = "label label-primary" })
                    @Html.ActionLink("Details", "Details", new { id = item.EnderecoId }, htmlAttributes: new { @class = "label label-primary" })
                    @Html.ActionLink("Delete", "Delete", new { id = item.EnderecoId }, htmlAttributes: new { @class = "label label-danger" })
                </td>
            </tr>
        }
    </tbody>

</table>


@section Scripts {
    <script>
        function findIndexEndereco() {
            $("#tbIndexEndereco").empty();

            $.ajax({
                type: "GET",
                url: "/Endereco/ObterPorLogradouro",
                datatype: "json",
                data: { "logradouro": $("#pesquisaIndexEndereco").val() },
                success: function (result) {

                    for (l = 0; l < JSON.parse(result).length; l++) {
                        $('#tbIndexEndereco').append(
                            `<tr>
                                    <td>${JSON.parse(result)[l].Uf}</td>
                                    <td>${JSON.parse(result)[l].Cidade}</td>
                                    <td>${JSON.parse(result)[l].Bairro}</td>
                                    <td>${JSON.parse(result)[l].Logradouro}</td>
                                    //<td>${(JSON.parse(result)[l].Complemento == null ? '' : JSON.parse(result)[l].Complemento)}</td>
                                    <td>${JSON.parse(result)[l].Cep}</td>
                                    <td>
                                        <a href='Endereco/Edit/${JSON.parse(result)[l].EnderecoId}' style='text-decoration:none' class='label label-primary' ; ">Editar</a>
                                        <a href='Endereco/Details/${JSON.parse(result)[l].EnderecoId}' style='text-decoration:none' class='label label-primary' ; ">Detalhar</a>
                                        <a href='Endereco/Delete/${JSON.parse(result)[l].EnderecoId}' style='text-decoration:none' class='label label-danger' ; ">Deletar</a>
                                    </td>
                                </tr>`
                        )
                    }
                }
            });

        }
    </script>
}